{% set name = "dtw-python" %}
{% set version = "1.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0947d5eed43bb6eec19325f294adf586defdd70b6ba4a49c2cf25408dcd59b87

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<36 or python_impl == 'pypy']
  entry_points:
    - dtw = dtw.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
    - numpy
    - setuptools
  host:
    - python
    - pip
    - numpy >=1.14
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy

test:
  imports:
    - dtw
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests
    - dtw --help

about:
  home: https://dynamictimewarping.github.io/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A comprehensive implementation of dynamic time warping (DTW) algorithms.

  description: |
    A comprehensive implementation of dynamic time warping (DTW)
    algorithms. DTW computes the optimal (least cumulative distance)
    alignment between points of two time series. Common DTW variants
    covered include local (slope) and global (window) constraints,
    subsequence matches, arbitrary distance definitions,
    normalizations, minimum variance matching, and so on. Provides
    cumulative distances, alignments, specialized plot styles, etc.
  doc_url: https://dynamictimewarping.github.io/python/
  dev_url: https://github.com/DynamicTimeWarping/dtw-python

extra:
  recipe-maintainers:
    - tonigi
