{% set name = "dtw-python" %}
{% set version = "1.1.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dtw-python-{{ version }}.tar.gz
  sha256: 887a67211275d2f9e70eb3b1319890cb5d7f9a8e0d68e5a5566664448d51ce26

build:
  number: 0
  skip: true   # [py2k]
  entry_points:
    - dtw=dtw.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - numpy >=1.19
    - python
    - scipy >=1.1
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - dtw
  commands:
    - pip check
    - dtw --help
  requires:
    - pip

about:
  home: https://DynamicTimeWarping.github.io
  summary: A comprehensive implementation of dynamic time warping (DTW) algorithms. DTW computes the optimal (least cumulative distance) alignment between points of two time series. Common DTW variants covered include local (slope) and global (window) constraints, subsequence matches, arbitrary distance definitions, normalizations, minimum variance matching, and so on. Provides cumulative distances, alignments, specialized plot styles, etc.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tonigi
