{% set name = "dtw-python" %}
{% set version = "1.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: eac5ab8431e7a054746ea64fe0c7f5f853e1e467bab0c94967fc8b80e32cd276
  #git_url: https://github.com/DynamicTimeWarping/dtw-python.git
  #git_rev: debug-ci

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [python_impl == 'pypy']
  entry_points:
    - dtw = dtw.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ stdlib("c") }}
    # - setuptools
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - scipy
    - numpy

# See https://github.com/conda-forge/yt-feedstock/blob/main/recipe/meta.yaml
# https://conda-forge.org/docs/maintainer/knowledge_base/

test:
  imports:
    - dtw
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests
    - dtw --help

about:
  home: https://dynamictimewarping.github.io/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: A comprehensive implementation of dynamic time warping (DTW) algorithms in Python.  DTW computes the optimal (least cumulative distance) alignment between points of two time series.  Common DTW variants covered include local (slope) and global (window) constraints, subsequence matches, arbitrary distance definitions,
    normalizations, minimum variance matching, and so on.  Provides cumulative distances, alignments, specialized plot styles, etc.
  description: DTW is a family of algorithms which compute the local stretch or compression to apply to the time axes of two timeseries in order to optimally map one (query) onto the other (reference). DTW outputs the remaining cumulative distance between the two and, if desired, the mapping itself (warping function). DTW
    is widely used for classification and clustering tasks, e.g. in bioinformatics, chemometrics, econometrics, and general timeseries mining.
  doc_url: https://dynamictimewarping.github.io/python/
  dev_url: https://github.com/DynamicTimeWarping/dtw-python

extra:
  recipe-maintainers:
    - tonigi
